### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by timwis**
I notice this is in npmjs already as a fork..can you pull it in to upstream?

### CODE REVIEW

**Comment by fiznool** [comment]
Happy to do so, but it only really makes sense if @tjwebb is happy to add me as an npm owner for the module?

**Comment by timwis** [comment]
Emailed @tjwebb and copied you as well as npmjs.org support per [their documentation](https://docs.npmjs.com/misc/disputes)

**Comment by tjwebb** [comment]
Sure, what's your npm username?

**Comment by fiznool** [comment]
fiznool

**Comment by tjwebb** [comment]
Should be all set

https://www.npmjs.com/package/backbone.basicauth/access

**Comment by fiznool** [comment]
Thanks @tjwebb. Updated package.json repo URLs and published 0.4.1.

**Pull request merged**
